### ISSUE TITLE
Rename exe/prompt to exe/compare_with_wikidata

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#23]
It's fairly standard to name the binary for a gem after the gem itself. I think `compare_with_wikidata` is also slightly more descriptive than `prompt`, which sounds like it might be something to do with your shell prompt.

**Comment by tmtmtmtm** [comment]
👍  for this change, though I suspect this is still a little back-to-front, and that we might be better off thinking of this the other way around (i.e. the subject should be Wikidata, and we then compare that with an external source, rather than starting from a scraper, or other random CSV file, and comparing with Wikidata). It's quite subtle, but I fear that it'll become a critical distinction at some point in the future, where if we're viewing it this way around, it'll take us down a slightly awkward path.
