### ISSUE TITLE
Error on Daff_us_senate

### ISSUE THREAD

**Issue by lucychambers** [everypolitician/compare_with_wikidata#40]
On: https://www.wikidata.org/wiki/User:Chris_Mytton/sandbox/daff_us_senate

We get this error: 

Error: Wikidata query "SELECT DISTINCT ?id (STRAFTER(STR(?item), STR(wd:)) AS ?wikidata_id)\nWHERE {\n ?item p:P39 ?mem .\n ?mem ps:P39 wd:Q13217683 .\n OPTIONAL { ?item wdt:P1157 ?id }\n OPTIONAL { ?mem pq:P580 ?startDate }\n OPTIONAL { ?mem pq:P582 ?endDate }\n FILTER (\n (BOUND(?startDate) && (?startDate >= \"2017-01-03T00:00:00Z\"^^xsd:dateTime)) {{!}}{{!" failed: 400 Bad Request

**Comment by chrismytton** [comment]
Looks like this is because the `{{!}}` are getting sent through to the query service. We'll need to do the opposite of what [this code is doing](https://github.com/everypolitician/compare_with_wikidata/blob/3e3c96c9359dc0fcc5bc987d5f6fa3c66dc0460e/templates/mediawiki.erb#L4) for incoming SPARQL queries.

**Comment by chrismytton** [comment]
I wonder if this could/should be fixed in https://github.com/everypolitician/mediawiki-page-replaceable_content, so that library would give you back the unescaped parameters to the mediawiki template?

**Comment by chrismytton** [comment]
So it turns out there are multiple levels to this problem.

1. The SPARQL parameter returned by mediawiki-page-replaceable_content still contains the `{{!}}` template. I've put in a hacky fix for that in https://github.com/everypolitician/compare_with_wikidata/commit/b067186e88d3deebf88a74036b510605bda80e29, but ideally mediawiki-page-replaceable_content would un-template parameters before returning them. The issue for that is https://github.com/everypolitician/mediawiki-page-replaceable_content/issues/3.
2. When the template call contains sub-templates it breaks the regex we're using. The issue for that is https://github.com/everypolitician/mediawiki-page-replaceable_content/issues/5.

I think the fix that I've done for 1. is Good Enough for now. So we need to decide the best course of action for fixing 2. I've included some options in https://github.com/everypolitician/mediawiki-page-replaceable_content/issues/5, which have varying degrees of hackyness vs time to fix.

**Comment by chrismytton** [comment]
This error should no longer be a problem now that #42 has been merged. Please re-open if you see it re-occur!
